version: "3"
services:
  mongo_db:
    image: skedaddle/mongo
    # Forward the mongodb port from the host to the container
    ports:
      - "27017:27017"
    env_file:
      - config/local.env

  api:
    # Install environment files
    env_file:
      - config/local.env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      # Map the Go source code folder
      - .:/go/src/app
      # Map the MongoDB data folder to the host
      - ./data:/data/db
