FROM kinano/go

ENV SRC_DIR=/github.com/kinano/go-mongo-docker

WORKDIR $SRC_DIR

# Copy source code
COPY . .

# On local DEV, we will use realize to hot reload our code changes in the container
ENTRYPOINT ${GOPATH}/bin/CompileDaemon \
    -directory=$SRC_DIR \
    -graceful-kill=true \
    -build="go build -o ./build/compiled_app" \
    -command="./build/compiled_app"